name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  DATABASE_URL: postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
  DSICORD_TOKEN: bot_token

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
